# Generated by Django 5.1 on 2024-06-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0002_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="visited_at",
            field=models.DateField(null=True),
        ),
    ]
