# Generated by Django 5.1 on 2024-06-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0003_marker_visited_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="photo",
            field=models.ImageField(null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="marker",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marker",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
